name: Setup KernelSU
description: Install official KernelSU from its main branch

runs:
  using: composite
  steps:
    - name: Download KernelSU
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        set -euo pipefail

        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

    - name: Enable Kernel Configs
      uses: ./.github/actions/set-kernel-config
      with:
        config_list: |
          CONFIG_KSU=y
