name: Build Xiaomi Pad 7 Pro GKI 6.1.138

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/prepare.yml
    with:
      config_file: .github/config/android14-6.1.json
      feature_set: SUSFS
      root_flavor: next
      root_commit: 234f6e040fcbca18b16d2398e1aa225712ec99ad
      susfs_commit: e287d59066380bf6de4396532d4a42edf4408701
      preserve_abi: true
      build_bypass: false
      os_patch_level: 2025-06
      variant: KernelSU-Next-muyu
    secrets: inherit
